# -*- coding: utf-8 -*-
"""Decission_tree_classifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXVfHgyhqPR1104UuKoq9WDLGKJkVhBi
"""

import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

dir(data)

data.data

data.feature_names

data.target

data.target_names

df = pd.DataFrame(np.c_[data.data , data.target],columns = [list(data.feature_names)+['target']])

df.head()

df.tail()

df.shape

"""split data"""

x = df.iloc[:,0:-1] # here we drop the last "target" column 
x

y = df.iloc[:,-1] # and assign the "target" column in y variable 
y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

print("the shape of x_train_data is :",x_train.shape)
print("the shape of x_test data is :",x_test.shape)
print("the shape of y_train data is :",y_train.shape)
print("thbe shape of y_test data is :",y_test.shape)

"""train decision tree classifier 

"""

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'gini')
model.fit(x_train,y_train)

model.score(x_test,y_test)

"""with feature scaling 

"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

sc.fit(x_train)

x_train_sc = sc.transform(x_train)
x_test_sc = sc.transform(x_test)

model2 = DecisionTreeClassifier(criterion = 'gini')

model2.fit(x_train_sc,y_train)
model2.score(x_test_sc,y_test)

patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

patient1 = np.array([patient1])
patient1

model.predict(patient1)

data.target_names

pred = model.predict(patient1)

if pred[0] ==0:
  print("you have cancer(malignant tumor)")
else:
  print("you has no cancer (malignant benign)")

